config/routes.rb
BackApp::Application.routes.draw do

  match 'posts/search' => 'posts#search'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'


  get 'posts/reply'
  get 'votes/handle'
  get 'users/showStats'
  get 'votes/showStats'
  get 'users/destroy'
  get 'votes/showHome'
  get 'sessions/destroy'
  post 'posts/addReply'
  post 'posts/search'




  resources :posts
  resources :users
  resources :sessions
  resource :votes

  root :to=> 'posts#index'
  root :controller => 'posts', :action => 'reply'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes , :dependent => :destroy
  validates :description, :presence => true
  validates :user_id, :presence => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  def index
    @posts = Post.find_all_by_postId(nil)
    @sortedpost = sortposts
    @title = 'Back Channel App - Home'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    if signed_in?
      @post = Post.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    else
      redirect_to '/signin' , :flash => {:info => "you have to signin before you can post!"}
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    if $current_user.nil? or $current_user.id != @post.user.id
      respond_to do |format|
        format.html {redirect_to '/posts', :flash => {:info => "You do not have the proper permissions for this operation"}}
      end
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = $current_user.posts.build(params[:post]);
    respond_to do |format|
      if @post.save
        format.html { redirect_to :to => 'posts#index' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to '/posts', notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy

    @post = Post.find(params[:id])
    @repliesToPost = Post.find_all_by_postId(@post.id)
    #delete each reply made to the post
    @repliesToPost.each do |eachReply|
      eachReply.destroy
    end

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end

  def reply
    if signed_in?

      @postid= params[:id]
      respond_to do |format|
        format.html
        format.json { render json: @post }
      end
    else
      respond_to do |format|
        format.html {redirect_to '/posts', :flash => {:info => "You have to sign in before you can reply"} }
      end
    end
  end

  def addReply
    @post = $current_user.posts.build(params[:post])
    @post.postId = params[:postId]
    respond_to do |format|
      if @post.save
        format.html { redirect_to '/posts'}
      end
    end
  end

  def search
    search_by =  params[:search_by]
    if(params[:search].to_s == "")
      respond_to do |format|
        format.html{redirect_to '/posts', :flash => {:info => "Search term cannot be empty"} }
      end
    else
      if search_by !="1" && search_by !="2"
        respond_to do |format|
          format.html{redirect_to '/posts', :flash => {:info => "Please check one of the radio buttons in search"} }
        end
      else
        if search_by =="1"  # search by post
          @posts = Array.new
          allposts = Post.all

          for eachpost in allposts do
            search_term = params[:search].to_s
            search_term_lower_case = search_term.downcase
            eachpost_description_lower_case = eachpost.description.downcase
            if(eachpost_description_lower_case.include?(search_term_lower_case))
              @posts << eachpost
            end
          end
        elsif search_by =="2"  # search by user
          @user = User.find_by_userName(params[:search])
          if @user.nil?
            @posts = Array.new
          else
            @posts = Post.find_all_by_user_id(@user.id)
          end
        end
        respond_to do |format|
          format.html  # search.html.erb
          format.json { render json: @posts }
        end
      end
    end
  end

  def sortposts
    # sorting the posts according to the weights
    sortedpost = Post.find_all_by_postId(nil)
    sortedpost.each do |post|
      vote_post = Vote.find_all_by_post_id(post.id)
      vote_count = vote_post.count
      time_difference_sec = Time.now.utc - post.created_at
      minutes  = time_difference_sec / 60
      hours = (minutes / 60).to_int
      days  = (hours / 24).to_int
      months = (days/30).to_int
      years =  (months/12).to_int
      score = 0

      if years > 0
        score = 0
      elsif months > 0
        if months < 3
          score = 4
        elsif months < 6
          score = 3
        elsif months < 9
          score = 2
        elsif months < 12
          score = 1
        end
      elsif days > 0
        if days < 5
          score = 10
        elsif days < 10
          score = 9
        elsif days < 15
          score = 8
        elsif days < 20
          score = 7
        elsif days < 25
          score = 6
        elsif days < 31
          score = 5
        end
      elsif hours > 0
        if hours < 4
          score = 16
        elsif hours < 8
          score = 15
        elsif hours < 12
          score = 14
        elsif hours < 16
          score = 13
        elsif hours < 20
          score = 12
        elsif hours < 24
          score = 11
        end
      elsif minutes > 0
        if minutes < 1
          score = 36
        elsif minutes < 2
          score = 35
        elsif minutes < 3
          score = 34
        elsif minutes < 4
          score = 33
        elsif minutes < 5
          score = 32
        elsif minutes < 6
          score = 31
        elsif minutes < 7
          score = 30
        elsif minutes < 8
          score = 29
        elsif minutes < 9
          score = 28
        elsif minutes < 10
          score = 27
        elsif minutes < 15
          score = 26
        elsif minutes < 20
          score = 25
        elsif minutes < 25
          score = 24
        elsif minutes < 30
          score = 23
        elsif minutes < 35
          score = 22
        elsif minutes < 40
          score = 21
        elsif minutes < 45
          score = 20
        elsif minutes < 50
          score = 19
        elsif minutes < 55
          score = 18
        elsif minutes < 60
          score = 17
        end
      else
        score = 37


      end
      post.weight = vote_count * 60 + 40 * score
      post.save

    end

    return sortedpost
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align="center">

    <%= f.label :description %><br />
    <%= f.text_area :description %>

    </div>
  <div class="actions" align="center">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1><div id="banner" align="center">Editing post</div></h1>

<%= render 'form' %>

<p align="center"><%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>  </p>

app/views/posts/index.html.erb
<html> <head>
  <style>

      .profile {
          width: 100%;
          margin-bottom: 0;
      }

      .main {
          width: 70%;
          padding: 1em;
      }

      .sidebar {
          width: 30%;
          padding: 1em;
          vertical-align: top;
          background: #ffc;
      }

      body{  	background: #FFF;
          color: #000;
          font: 80% Verdana, Geneva, Helvetica, Arial, sans-serif;}

      a{			color: #007700;}
      div.votes a {color: white;}

      textarea{		font: 1em "Courier New", monospace;}

      div#nav{		background-color: #007700;
          float: left;
          width: 16%;
          max-width: 16%;
          margin: 0 1.5% 0 .25%;
          padding: 4px 0px 10px 10px;
          font-weight: bold;
          font-size: 13px;
          line-height: 140%;
          overflow: hidden}

      div#nav a{		color:white;}


      div#wrapper{	width: 100%;}

      div#recent{  background-color: #f5f5f0;
          width: 100%;
          float: left;
          margin: .5% .5% .5% 0%;
          border-top: 1px solid #ccc;
          border-left: 1px solid #ccc;
          overflow: hidden;}
      div#recent1{
          width: 100%;
          float: left;
          margin: .5% .5% .5% 0%;
          overflow: hidden;}

      div#popular{	background-color: #f5f5f0;
          width: 100%;
          float: left;
          margin: .5% .5% .5% 0%;
          border-top: 1px solid #ccc;
          border-left: 1px solid #ccc;
          overflow: hidden;}
      .table,.th, .td
      {
          border: 1px solid black;
      }
      .center{  	background-color: #f5f5f0;
          width: 80%;
          text-align: left;
          margin: 0 .5% 0 .5%;
          border-top: 1px solid #ccc;
          border-left: 1px solid #ccc;
          padding: 5px;}


      .subcolumn1{ float:left;
          width: 49%;
          margin: .5% 0% .5% .5%;
          overflow: hidden;
          border-right: 1px solid #ccc}

      .subcolumn{
          width: 49%;
          margin: .0% 0% .5% .5%;
          overflow: hidden;
          border-right: 1px solid #ccc}

      .subcolumn2{	float: right;
          width: 49%;
          overflow: hidden;
          border-right: 1px solid #ccc}
      .question{	background-color: white;
          float: left;
          width: 96%;
          margin: .5% 2% .5% 0%;
          padding: 1%;
          overflow: auto}

      .question1{	background-color: white;
          float: left;
          width: 50%;
          margin: .5% 2% .5% 0%;
          padding: 1%;
          overflow: auto}

      .answer{	background-color: white;
          float: left;
          width: 85%;
          border: 2px solid #00FF00;
          margin: .5% 2% .5% 5%;
          padding: 1%;
          overflow: hidden;}

      .votes{ 	margin: 0px 5px 0px 0px;
          padding: 2%;
          float: left;
          color: #fff;
          text-align:center;}


      .columnhead{text-align: center;
          font-size: 110%;
          font-weight: bold;
          color: #007700;
          padding: 2px}

      #banner{	color: #fff;
          background: #007700;
          height: 34px;
          font-size: 1.1em;
          line-height: 2em;
          display: block;
          padding-top: 2px;
          text-indent: 30px;
          text-decoration: none;
          font-weight: bold;
          font-size: 18px;
          line-height: 24px;}



      .c0 {	border: 2px solid #000088;}
      .c1 {	border: 2px solid #0066aa;}
      .c2 {	border: 2px solid #008888;}
      .c3 {	border: 2px solid #007700;}
      .c4 {	border: 2px solid #99aa00;}
      .c5 {	border: 2px solid #bb7700;}
      .c6 {	border: 2px solid #cc0000;}
      .c7,.c8 {  border: 2px solid #ff0044;}

      .vc0 {	background: #000088;
          border: 2px solid #000088;}
      .vc1 {	background: #0066aa;
          border: 2px solid #0066aa;}
      .vc2 {	background: #008888;
          border: 2px solid #008888;}
      .vc3 {	background: #007700;
          border: 2px solid #007700;}
      .vc4 {	background: #99aa00;
          border: 2px solid #99aa00;}
      .vc5 {	background: #bb7700;
          border: 2px solid #bb7700;}
      .vc6 {	background: #cc0000;
          border: 2px solid #cc0000;}
      .vc7,.vc8 { background: #ff0044;
          border: 2px solid #ff0044;}

      .new {color: #993300;}
      .stale{	color: #999999;}
  </style>
</head>

<body>

<div id="banner" align="center">Live Question Tool: CSC517</div><br/>
<div style = "text-align: center;">

  <div class="search-box">
    <%= form_tag "posts/search", :method => 'get' do %>
        <p>
        <h2>Search for posts</h2>
        <%= text_field_tag :search, params[:search] %> <br/>
        <%= radio_button_tag :search_by, 1, false %>Search by Post
        <%= radio_button_tag :search_by, 2, false %>Search By User<br/>
        <%= submit_tag "Search", :name => nil %>
        </p>
    <% end %>
  </div>


  <!-- From this part on we display the posts and replies-->

  <%= link_to 'Post a New Question', :controller => 'posts' ,:action => 'new'  %>
</div>



<% @sortedpost.sort!{ |a,b | b.weight <=> a.weight}  %>


<div id = "recent">
  <div class="columnhead"></div>
  <% @sortedpost.each do |post| %>
      <div>
        <%if($current_user!=nil)%>
            <%if(post.user_id).eql?$current_user.id%>
                <div class="question c5 stale" align="left">
                  <div class="votes vc1">
                    <%= link_to post.votes.count, votes_handle_path(:id =>post.id)%>
                  </div>

                  <b><%= post.user.userName %></b>:
                  <%= post.description %><br/><br/>
                  <i>---posted <%= time_ago_in_words(post.created_at)%> ago.</i><br/>
                  <%= link_to 'Edit', edit_post_path(post) %>
                  <%= link_to 'Delete',  posts_destroy_path(:id =>post.id) %>
                  <b align="right"><%= link_to 'Reply', posts_reply_path(:id =>post.id)%></b>


            <%else%>
                <div class="question c5 stale" align="left">
                  <div class="votes vc1">
                    <%= link_to post.votes.count, votes_handle_path(:id =>post.id)%>
                  </div>
                  <b><%= post.user.userName %></b>:
                  <%= post.description %> <br/><br/>
                  <i>---posted <%= time_ago_in_words(post.created_at)%> ago.</i><br/>
                  <b align="right"><%= link_to 'Reply', posts_reply_path(:id =>post.id)%></b>

                  <%if $current_user.user_type == "Admin"%>
                      <%= link_to 'Delete',  posts_destroy_path(:id =>post.id) %>
                  <%end%>

            <%end%>
            <br/>
            <% Post.find_all_by_postId(post.id).each do |reply|%>
                <br/>
                <div class="votes vc3">
                  <%= link_to reply.votes.count, votes_handle_path(:id =>reply.id)%>
                </div>
                <b><%= reply.user.userName %></b>:
                <%= reply.description %> <br/><br/>
                <i>---posted <%= time_ago_in_words(reply.created_at)%> ago.</i><br/>
                <%if reply.user.id == $current_user.id%>
                    <%= link_to 'Edit', edit_post_path(reply) %>
                    <%= link_to 'Delete', posts_destroy_path(:id => reply.id)%>


                <%else%>


                    <%if $current_user.user_type == "Admin"%>
                        <%= link_to 'Delete',   posts_destroy_path(:id =>reply.id) %>
                    <%end%>
                <%end%>
            <%end%>
            </div>
        <%else%>

            <div class="question c5 stale " align="left">
              <div class="votes vc1">
                <!--<%= link_to post.votes.count, votes_handle_path(:id =>post.id)%>-->
                <%= post.votes.count%>
              </div>
              <%= post.user.userName %>:
              <%= post.description %>  <br/>
              <i>---posted <%= time_ago_in_words(post.created_at)%> ago.</i><br/>
              <% Post.find_all_by_postId(post.id).each do |reply|%>
                  <div class="votes vc3">
                    <%= reply.votes.count%>
                  </div>
                  <b><%= reply.user.userName %></b>:
                  <%= reply.description %> <br/>
                  <i>---posted <%= time_ago_in_words(reply.created_at)%> ago.</i><br/>

              <%end%>
            </div>
        <%end%>
        </div>
  <%end%>

  </div>



  <p style="text-align: center;">
    <%if($current_user.nil? )%>
        <%= link_to 'Sign In', :controller => 'sessions' ,:action => 'new'  %>

    <%else%>
        <%if $current_user.user_type=="Admin"%>
            <%= link_to 'Sign Out', sessions_destroy_path %>
            <%= $current_user.userName%> |
            <%=link_to'Admin Statistics',votes_showStats_path %>
        <%else %>
            <%= link_to 'Sign Out', sessions_destroy_path %>
            <%= $current_user.userName%>
        <%end%>
    <%end%>
  </p>

</body>


</html>

app/views/posts/new.html.erb
<h1 align="center"><div id="banner">New post</div></h1>

<%= render 'form' %>

<p align="center"><%= link_to 'Back', posts_path %></p>

app/views/posts/reply.html.erb
<H1><div id="banner" align="center">Reply</div></H1>
<%= form_for(:post, :url => 'addReply') do |f| %>

    <div class="field" align="center">
    <%= hidden_field_tag :postId, @postid  %>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions" align="center">
    <%= f.submit %>
  </div>
<% end %>

<p align="center"><%= link_to 'Back', posts_path %></p>

app/views/posts/search.html.erb
<p id="notice"><%= notice %></p>

<p>
<h1><div id="banner"> <b>Search Results:</b></div> </h1>

<%if @posts.count ==0 %>
    <b> No search hits </b>
<%end%>

<%if @posts%>

    <% @posts.each do |post| %>


          <div class="question1 c5 stale" align="left">

            <br />
            <b><%= post.user.userName %> </b> :
            <%= link_to post.description, post%>
          </div>

    <%end%>
<%end%>


</p>

app/views/posts/show.html.erb
<html>
<h1 div id="banner">Thread Post</h1> </div></br>
<p id="notice"><%= notice %></p>
<%puts @post.postId%>
<%if @post.postId != nil%>
    <% parent = Post.find_by_id(@post.postId)%>
    <%puts parent.postId%>
    <% @post = parent %>
<%end%>


  <div class="question1 c5 stale" align="left">
<b><%= @post.user.userName %></b>:
<%= @post.description %>  <br/>
<i>---posted <%= time_ago_in_words(@post.created_at)%> ago.</i><br/>
<% Post.find_all_by_postId(@post.id).each do |reply|%>
    <b><%= reply.user.userName %></b>:
    <%= reply.description %> <br/>
    <i>---posted <%= time_ago_in_words(reply.created_at)%> ago.</i><br/>


<%end%>
    </div>
    <div id=recent1>
    <p style="text-align: center;">
    <%= link_to 'Back', posts_path %> </p><br/> </div>
  </html>