config/routes.rb
BackApp::Application.routes.draw do

  match 'posts/search' => 'posts#search'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'


  get 'posts/reply'
  get 'votes/handle'
  get 'users/showStats'
  get 'votes/showStats'
  get 'users/destroy'
  get 'votes/showHome'
  get 'sessions/destroy'
  post 'posts/addReply'
  post 'posts/search'




  resources :posts
  resources :users
  resources :sessions
  resource :votes

  root :to=> 'posts#index'
  root :controller => 'posts', :action => 'reply'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def handle
    @flag = 0
    @post = Post.find_by_id(params[:id])
    if $current_user.id != @post.user_id

      votecheck = Vote.find_by_post_id_and_user_id(@post.id,$current_user.id)
      if ( votecheck.nil?)
        voteForPost(@post)
        respond_to do |format|
          format.html{redirect_to '/posts', :flash => {:info => "Your vote has been registered"}}
        end
      else
        respond_to do |format|
          format.html{redirect_to '/posts', :flash => {:info => "you have voted for this post already "}}
        end
      end
    else
      respond_to do |format|
        format.html{redirect_to '/posts', :flash => {:info => "You cannot vote for your own post "}}
      end
    end
  end

  def voteForPost(post)
    @newVote = Vote.new
    @newVote.user_id = $current_user.id
    @newVote.post_id = @post.id
    @newVote.save
  end
  def showStats
     respond_to do |format|
       format.html{}
     end

  end

  def showHome
    redirect_to '/posts'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/showStats.html.erb
<html>
<h1 align="center"> <div id="banner">Admin Statistics Page</div></h1>  </br></br></br>
<body>
<%@users=User.all%>

   <div id="recent">
  <table border="1px solid green " cellspacing="4" align="center"  >

    <th> User Name</th>
    <th> No. of Posts Created</th>
    <th> Total no. of Votes </th>
    <th>Delete User</th>

    </tr>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.userName%></td>
          <td><%= user.posts.count %> </td>
          <%@posts=user.posts.all%>
                <%@sum=0%>
          <% @posts.each do |post| %>
              <%if post.postId==nil%>
                  <%(@sum+=post.votes.count)%>
              <%end%>
          <%end%>
          <td><%=@sum%></td>
          <b><td><%=link_to'Destroy',users_destroy_path(:id =>user.id)%></td></b></br>
        </tr>
    <% end %>
  </table>
  </div>
</body>
</html>
<p align="center"><%=link_to'Home Page',votes_showHome_path%> |
<%=link_to'Sign Up',new_user_path%></p> </br>